apiVersion: v1
kind: Service
metadata:
  name: login-app-service
spec:
  type: NodePort
  selector:
    app: login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
